to resolve github issue#38
AOMediaCodec/iac pull request #45
Opened 2022-04-19 07:16 UTC by sunghee-hwang

2022-04-28 23:32 UTC, tdaede requested changes

2022-04-28 23:32 UTC, tdaede commented on index.bs
> +- Demixing_Info_OBUs (with OBU syntax) shall (or may) be stored as a new sample group having [=grouping_type=], 'dmpm'.
We need to be more specific here - pick SHALL or MAY, not both.

2022-04-29 01:06 UTC, sunghee-hwang commented on index.bs
> +- Demixing_Info_OBUs (with OBU syntax) shall (or may) be stored as a new sample group having [=grouping_type=], 'dmpm'.
I would pick "may"

2022-04-29 07:44 UTC, tdaede approved these changes

2022-05-02 21:32 UTC, merged