Updated Introduction section
AOMediaCodec/iac pull request #47
Opened 2022-04-21 04:07 UTC by sunghee-hwang

2022-04-28 23:35 UTC, tdaede requested changes

2022-04-28 23:35 UTC, tdaede commented on index.bs
> -<center><img src="Conventional Mono or Stereo Encoding & Decoding Model.png"></center>
Was it your intent to remove the encoding and decoding model images? If so we should delete them from the repo as well.

2022-04-29 01:07 UTC, sunghee-hwang commented on index.bs
> -<center><img src="Conventional Mono or Stereo Encoding & Decoding Model.png"></center>
I deleted the relevant files.

2022-04-29 07:44 UTC, tdaede approved these changes

2022-04-29 07:44 UTC, merged